targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          import: flutter_artech
          fragments_glob: graphql/**.fragment.graphql
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/*.{query,subscription,mutation}.graphql
              output: lib/api/graphql_api.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - custom_parser_import: 'package:flutter_artech/flutter_artech.dart'
              graphql_type: Date
              dart_type: DateTime
            - custom_parser_import: 'package:flutter_artech/flutter_artech.dart'
              graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: JSON
              dart_type: object
            - custom_parser_import: 'package:full_house_app/utils/coercers.dart'
              graphql_type: Upload
              dart_type:
                name: MultipartFile
                imports:
                  - 'package:http/http.dart'
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
          nullable: true
